mejuri-inc/flowcommerce_spree

app/models/spree/order_decorator.rb, lib/flowcommerce_spree/api.rb
When going to a syncrhonized flow order edit page the application is raising an exception like: `NoMethodError: undefined method `price_not_found' for Flow:Module`. This is because the method `Spree::Order#flow_line_item_price` is not able to find the line item associated to the variant and therfore tries calling to the `Flow.price_not_found`
Currently the order is storing the line_items information within the `meta` column, and the value stored within the `item_number` is the variant's sku instead of the ID.
Additionally, changing the `Flow#price_not_found` to `n/a`. It is in the only place it is being called so I think we should be ok Hardcoding the 'n/a' here.
Seems like it is how it should be working. Another option would be changing the Flow Order's sync method to store the id …
=> [NO TICKET] order line item price fix

Gemfile, spec/dummy/app/models/spree/product_decorator.rb, spec/dummy/config/environments/test.rb, spec/factories/spree/spree_options.rb, spec/factories/spree/spree_products.rb, spec/factories/spree/spree_shipping_categories.rb, spec/factories/spree/spree_states.rb, spec/factories/spree/spree_stock_locations.rb, spec/factories/spree/spree_variants.rb, spec/factories/spree/spree_zones.rb, spec/models/spree/product_spec.rb, spec/models/spree/variant_spec.rb, spec/rails_helper.rb, spec/support/database_cleaner.rb
Adding a little more coverage along with some factories that will come in handy for future specs.
- Adding new specs for Spree::Variant and Spree::Product methods.
- Adding some new factories for products, variants and related records.
- Configuring database_cleaner to properly keep the DB clean between specs.
We need to increase coverage.
Nothing worth mentioning.
=> [TEC-4667] product variant model specs

.github/workflows/main.yml, Gemfile, flowcommerce_spree.gemspec
We were manually installing bundler 1.17.3 version, but the `ruby/setup-ruby` action was using by default the latest version of bundler, which is not compatible with Rails 4.1.x, causing failures.
Also, the gemspec hasn't been added to the Gemfile, which was causing wrong dependency management by the bundler.
Specifying bundler 1.17.3 version to be used by the `ruby/setup-ruby` action and adding gemspec to the Gemfile.
Also added `bundler-cache` to be used by `ruby/setup-ruby` to boost the action start time.
=> Fix the use of bundler by GitHub Actions and adding gemspec to the Gemfile

app/models/spree/address_decorator.rb, app/models/spree/order_decorator.rb, lib/flowcommerce_spree/webhook_service.rb, spec/models/spree/order_spec.rb
Adding methods to create ship and bill address for Flow Orders.
- Adding new **flow_ship_address** and **flow_bill_address** methods to Spree::Order that returns a Spree::Address record with information loaded from Flow's data stored in meta.
- Adding new **prepare_flow_addresses** method to Spree::Order that creates/update the Spree::Address records based on flow information stored in the meta tag and returns the records's IDs, which the webhook uses to update the order. This is done this way in order to reduce the amount of DB calls made.
- Extending webhook **hook_order_upserted_v2** to call prepare_flow_addresses and set the order's email based on flow data.
We should save the ship and bill address associated to the order if we want Spree and Fulfill integration to work properly.
The …
=> [NO TICKET] persists flow address

README.md, app/models/spree/flow_io_product_decorator.rb, lib/flowcommerce_spree/version.rb, spec/models/spree/product_spec.rb
We are aiming to have in production these changes https://github.com/mejuri-inc/mejuri-web/pull/775. However; The version v0.0.1 is decorating that method and therefore the changes from https://github.com/mejuri-inc/mejuri-web/pull/775 are not being applied. These changes have been included into flowcommerce_spree within the `develop` branch which are not ready to be pushed into production yet.
The main issue is that we want to go live with these changes today (February 18th 2021) but we cannot use `develop` branch. 
Introducing changes from commit https://github.com/mejuri-inc/flowcommerce_spree/pull/16/commits/b94821f0bd66d82b79cfe56d2ec58466b91e742e (from develop branch) for a temporary usage.
The easiest solution to have these changes until the new version of flowcommerce_spree goes …
=> [TEC-4792] Configuring price_range to return min/max only

Gemfile, app/models/spree/calculator/flow_io.rb, app/models/spree/calculator/shipping/flow_io.rb, app/services/flowcommerce_spree/order_sync.rb, config/rails_best_practices.yml, lib/flowcommerce_spree/engine.rb, lib/flowcommerce_spree/webhook_service.rb, spec/factories/spree/spree_calculators.rb, spec/factories/spree/spree_orders.rb, spec/factories/spree/spree_shipments.rb, spec/factories/spree/spree_shipping_methods.rb, spec/models/spree/calculator/flow_io_spec.rb, spec/models/spree/calculator/shipping/flow_io_spec.rb
For orders that are associated to a Flow Experience, the shipping is not being handled/calculated within Spree. Flow will be processing the order on their side and sharing the order's details with Spree, which are stored in the `meta` column. Spree needs to create the shipping for the order using that information retrieved from Flow.
- Adding a new Shipping Calculator that Spree will use to create the shipment based on Flow's information stored within the order's `meta` column.
- Configuring webhook order_upseart_v2 to perform the following actions:
- create proposed shipments : Using the Spree::Stock::Coordinator will create the shipments, and thanks to the ShowroomSplitter it will also update the line item's stock_location_id.
- update shipments amount : This has to be called in order …
=> [TEC-4453] Adding Flow IO Shipping calcualtor and renaming tax calculator to match naming convention

app/controllers/flowcommerce_spree/orders_controller.rb, app/services/flowcommerce_spree/order_sync.rb, app/services/flowcommerce_spree/order_updater.rb, config/routes.rb, lib/flowcommerce_spree/engine.rb, lib/flowcommerce_spree/webhook_service.rb, spec/controllers/flowcommerce_spree/orders_controller_spec.rb, spec/flowcommerce_spree/order_updater_spec.rb, spec/flowcommerce_spree/webhook_service_spec.rb, spec/rails_helper.rb, spec/support/controller_requests.rb
For orders associated to a Flow experience we are using Flow's checkout; however, upon completing the checkout the user is redirected to our Thank you page hosted in Mejuri FE.
All the information submitted in the Flow's checkout is being propagated to Spree thanks to webhooks; However, some of these webhooks can take up to 5 minutes according to Flow, which might generate unwanted experiences for the user. Like seeing their order still open.
- Adding a new proxy endpoint `/flow/order-completed` between Flow and our Thank you page. This endpoint will update the order's information by calling Flow's API and then proceed to complete the order before redirecting the user to our thank you page.
- For this endpoint to be available we need to prepend Flow routes instead of append. This is …
=> [TEC-4958] base changes to handle thank you page redirection

app/services/flowcommerce_spree/order_updater.rb
After completing the checkout on flow the user gets redirected to Spree thank you page. Before reaching the thank you page we have configured a proxy endpoint which pulls the order's information from flow updating at that moment and after that it redirects the user to the thank you page.
Unfortunately this proxy method is not properly closing the order so there are a couple of actions not being performed at that point like leaving the order "open", not triggering the stock allocation or sending the confirmation email.  
By calling the `finalize_order` method which basically closes the order setting it as completed.
Calling the `finalize_order` method before redirecting the user to the thank you page will help us with:
- setting the order's completed_at attribute which will tell the store …
=> [TEC-4958] Thank you page redirection order finalization.

lib/flowcommerce_spree.rb, lib/flowcommerce_spree/engine.rb
When trying to run the application within an environment where it does not have any FLOW related environment variable set it raises an error.
By forcing the ENV['FLOW_TOKEN'] to a default value. 
The best solution would be to have a way of somehow configuring to avoid running any single line of code associated to Flow if the environment variable is not set; However I did not find any easy way of doing it.
Setting this default value in the initializer we make sure that it will be available. The issue is that we are using flowcommerce ruby-sdk gem, which requires this FLOW_TOKEN to be present (https://github.com/flowcommerce/ruby-sdk/blob/master/lib/flow_commerce/client.rb). Having this default will not stop Spree from trying calls, but at least it will not explode.
nothing worth mentioning …
=> [NO-TICKET] defauling FLOW_TOKEN environment variable to avoid errors

app/models/spree/flow_io_order_decorator.rb, app/models/spree/gateway/flow_io.rb, lib/flow/simple_gateway.rb, lib/flowcommerce_spree/logging_http_client.rb, lib/flowcommerce_spree/webhook_service.rb, spec/factories/flow_io/authorization_reference.rb, spec/factories/flow_io/capture.rb, spec/factories/flow_io/money.rb, spec/factories/flow_io/refund.rb, spec/factories/spree/gateway/flow_io.rb, spec/factories/spree/spree_payments.rb, spec/models/spree/gateway/flow_io_spec.rb
Adjusted Spree::Gateway::FlowIo.refund method to call client.refunds.post and return an ActiveMerchant::Billing::Response, either successful, or failed.
Adjusted error handling on the FlowcommerceSpree::LoggingHttpClient.
=> [TEC-4525] Create refund method for flow.io gateway

app/controllers/concerns/current_zone_loader_decorator.rb, spec/dummy/app/models/spree/app_configuration_decorator.rb
The current_session is returning an error since it is trying to access the preference `debug_request_ip_address` which is no longer available.
By removing leftover pieces of code.
=> [NOTICKET] Removing code related to leftovers of default_request_ip_address Spree preference

app/overrides/spree/admin/order_sidebar_summary_flow_link.rb, app/overrides/spree/admin/products/order_price_flow_message.rb, lib/flowcommerce_spree/engine.rb
Even though we have configured calculators, and gateways to make sure to update the order's date and create associated records to it based on the information pulled from Flow. The agent has no easy/quick way to identify if an order is associated to Flow.
Another issue we have is that the product's prices are handled within Flow using pricebooks for each experience and therefore that information is not available within the product's price book.
By adding some overrides to add simple messages with links to the Flow's console.
It would be the simplest solution while providing the administrator a quick vay of validating the information within flow if needed.
**Order's edit page:**
**Order's price list**
=> [DL-72] Adding some texts within Order's side bar and order's prices to link the user to Flow

.rubocop.yml, README.md, app/services/flowcommerce_spree/webhooks/card_authorization_upserted_v2.rb, spec/factories/flow_io/card.rb, spec/factories/flow_io/card_authorization.rb, spec/factories/flow_io/payment_method.rb, spec/services/flowcommerce_spree/webhooks/capture_upserted_v2_spec.rb, spec/services/flowcommerce_spree/webhooks/card_authorization_upserted_v2_spec.rb
CardAuthorizationUpsertedV2 changes:
- errors accessor is now only reader
- only one param is received - data (no more opts hash)
- changed `@card_auth` to `@data` for consistency with other webhook handlers
Added `FlowIo` card, card_authorization and payment_method factories.
=> [DL-80] CardAuthorizationUpsertedV2 specs

.rubocop.yml, README.md, app/models/spree/flow_io_order_decorator.rb, app/services/flowcommerce_spree/webhooks/capture_upserted_v2.rb, app/services/flowcommerce_spree/webhooks/card_authorization_upserted_v2.rb, spec/factories/flow_io/card.rb, spec/factories/flow_io/card_authorization.rb, spec/factories/flow_io/payment_method.rb, spec/factories/spree/spree_payment_capture_events.rb, spec/services/flowcommerce_spree/order_sync_spec.rb, spec/services/flowcommerce_spree/webhooks/capture_upserted_v2_spec.rb, spec/services/flowcommerce_spree/webhooks/card_authorization_upserted_v2_spec.rb
Spree::Order.flow_io_total_amount and `flow_io_balance_amount` methods now are returning 0 when amount is `nil`
Spree::Order.flow_io_experience_key is converting amount.to_d if it is a String
CaptureUpsertedV2 changes:
- errors accessor is now only `reader`
- only one param is received - `data` (no more `opts` hash)
- added order number param presence validation in `data`
- for simplification, separated some code from `process` method into the `upsert_order_captures` method
=> [DL-80] Capture_upserted_v2 webhook event handler specs and polishing

app/models/spree/flow_io_order_decorator.rb, spec/models/spree/order_spec.rb
When exporting the order to Flow I was thinking of using a more accurate method to identify if the order is effectively associated to flow or not.
Introducing a new `flow_order_with_payments?` method for the order. This methods checks first if there is a completed payment and then validates it's type. If the payment's type is effectively the same as Flow is using then it will return true; However if it is not then it will return false.
I think it is worth testing the payment's data since we could remove the order's metadata by error. However the payment is a little more difficult to delete.
=> [TEC-4443] Adding flow_order? validation method that will help identifying if order is associated to flow.

app/models/spree/calculator/shipping/flow_io.rb
Flow Orders are currently showing a wrong Shipping Estimated and Free shipping threshold within the Cart. We need a way to configure these values for flow orders.
By adding preferences **lower_boundary** and **charge_default** to the Shipping::Calculator::FlowIo.
The best solution would be to obtain these those values from Flow. However doing so will probably require more code changes which due to times we are going to handle in the near future in in a new ticket.
This configuration will only work for Spree side. If we want those values to also apply to the checkout we have to replicate them in Flow's configuration.
=> [DL-276] Adding charge_default and lower_boundary to the shipping FlowIo calculator

app/controllers/concerns/current_zone_loader_decorator.rb, app/controllers/flowcommerce_spree/orders_controller.rb, app/models/spree/zones/flow_io_product_zone_decorator.rb, app/services/flowcommerce_spree/order_updater.rb, spec/controllers/flowcommerce_spree/orders_controller_spec.rb
When Flow experience is archived, Spree will still keep loading the experience from the session which will eventually start raising errors since Flow will not allow new sessions to be requested. 
By doing a couple of changes to avoid loading experiences that are not active.
- CurrentZoneLoader#current_zone method will check for the zone's status when loading the zone using the session's stored name. This way if the zone is archived it will try loading a new zone.
- OrderUpdater#complete_order: to accept requests even when the zone's status is in archiving status.
By restricting the current_zone to only use "active" zones we make sure that the experience for users that are not in the checkout will stay updated based on the zone's status. Flow is currently not blocking nor raising an error …
=> [DL-67] Small change on current_zone_loader module to only load active zones for Flow

app/controllers/concerns/current_zone_loader_decorator.rb, app/models/spree/app_configuration_decorator.rb, lib/flowcommerce_spree/session.rb
The Geolocalization by IP is not working properly on all scenarios.
Changing session creation strategy  based on IP to country.
The behavior within the rest of the application is handled based on country. Changing this strategy to country should not bother us. In the future we can also support using IP in case we want to.
=> [DL-321] Changing Session creation strategy to use country ISO code instead of request IP

app/models/spree/gateway/flow_io.rb, spec/models/spree/gateway/flow_io_spec.rb
When trying to create a new return we are getting an error. The reason behind it is because FlowIo gateway does not have the **credit** method specified.
- Setting `payment_profiles_supported?` to return false.
- Adding new `Spree::Gateway::FlowIo#credit`. The method reuses part of the refund's logic. In order to follow the same logic as other gateways, this credit method should not create a transaction, but relay on the `Payment::Processing#credit!` to do it instead.
- Updating `Spree::Gateway::FlowIo#map_refund_to_payment` to set the source as the original payment (for consistency with other payments)
- The reason to configure `payment_profiles_supported?` to return false is because within the `Payment::Processing#credit!` Spree is sending different params depending on this value when …
=> [DL-499] Adding new credit method to FlowIo Gateway.

app/services/flowcommerce_spree/order_sync.rb, spec/services/flowcommerce_spree/order_sync_spec.rb
There is a very specific scenario where if a product with variants has a master variant with flow data, but none of it's variants has flow data, when the user adds the product to the cart and goes to the Flow's checkout it will be charge the variant's `cost_price` instead of the price.
Changing the default value sent when redirecting the user to the Flow's checkout to use the variant's price instead of the cost_price.
This should not be the final solution though. Probably we can avoid allowing the user to add the product to the cart (or showing the variant / PDP) when no flow price is present. But I would tackle that improvement separately to this simple change.
This change is not the best either, but it is better than charging the cost_price if for some reason the scenario happens.
=> [DL-517] Updating OrderSync#add_item method to send variant price instead of cost_price

app/controllers/flowcommerce_spree/orders_controller.rb, app/services/flowcommerce_spree/order_sync.rb, lib/flowcommerce_spree/version.rb, spec/controllers/flowcommerce_spree/orders_controller_spec.rb, spec/dummy/app/models/spree/order_decorator.rb, spec/services/flowcommerce_spree/order_sync_spec.rb
We want to share the order's locale with Flow so when the user is redirected back to the Store they will keep the selected preference.
- Extending the `OrderSync` to include the order's locale when creating the redirection urls.
- Updating the `FlowcommerceSpree::OrdersController#order_completed` endpoint to include the order's locale within the thank you page url when redirecting the user. 
This is the simplest solution so far, since it requires very little changes.
The order's `Spree::Order#locale_path` implementation will be included in the main app and will return the order's stored locale.
=> [DL-614] Adding support to include country_locale within the redirection routes when synchronizing order with Flow

app/controllers/flowcommerce_spree/orders_controller.rb
When user completes Flow's checkout, it is being redirected to the this order_completed endpoint. At this point, the flow is broken due to the bag_order returning a nil object instead of an order.
We don't need in this endpoint those actions, because of that I am completely avoiding them.
We remove unnecessary code.
=> [DL-614] Avoid prepare_order and before_render within order_completed endpoint.

app/services/flowcommerce_spree/order_sync.rb, app/services/flowcommerce_spree/order_updater.rb, spec/factories/spree/spree_adjustment.rb, spec/factories/spree/spree_promotion.rb, spec/factories/spree/spree_promotions_actions.rb, spec/services/flowcommerce_spree/order_sync_spec.rb, spec/services/flowcommerce_spree/order_updater_spec.rb
In order to support BFCM promotions in flow, we need to send the discounts information to them so they can show it in the checkout
Map the discount data to the payload sent to flow
=> [DL-674] - Send promotion info to flow

app/helpers/spree/core/controller_helpers/flow_io_order_helper_decorator.rb
From time to time we are having issues with the session_current. This is because it is calling this method `adjust_zone_and_ip` which is updating almost always the last_ip_address. 
Changing code to only update `last_ip_address` when it is different from what it is stored.
Will get us less updates to the database each time it is called.
=> [DL-874] change on adjust_zone_and_ip method to avoid updating last_ip_address almost allways, and instead only when needed

app/services/flowcommerce_spree/webhooks/capture_upserted_v2.rb, lib/flowcommerce_spree/version.rb, spec/controllers/users/sessions_controller_spec.rb, spec/factories/flow_io/order_address.rb, spec/factories/spree/spree_payment_method.rb, spec/factories/spree/spree_payments.rb, spec/services/flowcommerce_spree/order_updater_spec.rb, spec/services/flowcommerce_spree/webhooks/capture_upserted_v2_spec.rb
There is an issue with the sync of klarna payments with the new logic of placeholder payment. The validation was over the flow payments instead of the order payments, so it was still ignoring the captured upserted event.
Removes the validation for flow payments and improves the code
=> [UDL-760] - Fixed klarna payment sync for flow orders
